import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const ORIGINS=new Set(["https://chachinn.github.io","http://localhost:3000","http://localhost:5173","http://127.0.0.1:3000","http://127.0.0.1:5173"]),HOST="www.aozora.gr.jp",DEFAULT_MAX=1600,HARD_MAX=2400,MIN=300;
function cors(o:string|null){const a=o&&ORIGINS.has(o)?o:"https://chachinn.github.io";return{"Access-Control-Allow-Origin":a,"Access-Control-Allow-Headers":"apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"}}
function json(body:unknown,status=200,o:string|null=null){return new Response(JSON.stringify(body),{status,headers:{...cors(o),"Content-Type":"application/json; charset=utf-8","Cache-Control":status===200?"public, max-age=86400":"no-store"}})}
function keys(){const raw=Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"",out=new Set<string>();if(!raw)return out;try{const p=JSON.parse(raw);if(typeof p==="string")out.add(p);else if(Array.isArray(p))p.forEach(v=>typeof v==="string"&&out.add(v));else if(p&&typeof p==="object")Object.values(p).forEach(v=>typeof v==="string"&&out.add(v))}catch{raw.split(",").map(v=>v.trim()).filter(Boolean).forEach(v=>out.add(v))}return out}
function validUrl(v:unknown){if(typeof v!=="string")return null;try{const u=new URL(v);if(u.protocol!=="https:"||u.hostname!==HOST||!/^\/cards\/\d+\/files\/[A-Za-z0-9_\-.]+\.html$/i.test(u.pathname))return null;u.hash="";u.search="";return u}catch{return null}}
function entities(s:string){const named:Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" "};return s.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi,(_,t:string)=>{if(t[0]==="#"){const h=t[1]?.toLowerCase()==="x",n=Number.parseInt(t.slice(h?2:1),h?16:10);return Number.isFinite(n)?String.fromCodePoint(n):""}return named[t.toLowerCase()]??`&${t};`})}
function charset(ct:string,b:Uint8Array){const h=ct.match(/charset\s*=\s*([^;\s]+)/i)?.[1]?.replace(/["']/g,"").toLowerCase();if(h)return h;const p=new TextDecoder("ascii").decode(b.slice(0,4096));return p.match(/charset\s*=\s*["']?([^"'\s/>]+)/i)?.[1]?.toLowerCase()||"utf-8"}
function decode(b:Uint8Array,ct:string){const c=charset(ct,b),label=/shift[_-]?jis|sjis|windows-31j|ms932/i.test(c)?"shift_jis":"utf-8";try{return new TextDecoder(label).decode(b)}catch{return new TextDecoder("utf-8").decode(b)}}
function main(html:string){const m=html.search(/<div[^>]*class=["'][^"']*main_text[^"']*["'][^>]*>/i);if(m<0)return"";const s=html.indexOf(">",m)+1;if(s<=0)return"";const tail=html.slice(s),e=tail.search(/<div[^>]*class=["'][^"']*(?:bibliographical_information|notation_notes|after_text)[^"']*["'][^>]*>/i);return e>=0?tail.slice(0,e):tail}
function paragraphs(html:string){const m=main(html);if(!m)return[] as string[];return m.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,"").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,"").replace(/<rt\b[^>]*>[\s\S]*?<\/rt>/gi,"").replace(/<rp\b[^>]*>[\s\S]*?<\/rp>/gi,"").replace(/<br\s*\/?>/gi,"\n").replace(/<\/(?:p|div|h\d)>/gi,"\n").replace(/<[^>]+>/g,"").split("\n").map(l=>entities(l).replace(/[\t\r ]+/g," ").trim()).filter(Boolean).filter(l=>!/^(底本|入力：|校正：|青空文庫作成ファイル|［＃)/.test(l))}
function passage(ps:string[],max:number){const out:string[]=[];let chars=0;for(const p of ps){if(chars>=max&&chars>=MIN)break;const remain=max-chars;if(remain<=0)break;if(p.length<=remain){out.push(p);chars+=p.length}else{const slice=p.slice(0,remain),end=Math.max(slice.lastIndexOf("。"),slice.lastIndexOf("！"),slice.lastIndexOf("？")),safe=end>=Math.min(remain*.55,remain-1)?slice.slice(0,end+1):slice;if(safe.trim())out.push(safe.trim());chars+=safe.length;break}}return{paragraphs:out,text:out.join("\n\n"),charCount:chars}}
Deno.serve(async(req:Request)=>{const o=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(o)});if(req.method!=="POST")return json({error:"Method not allowed"},405,o);if(o&&!ORIGINS.has(o))return json({error:"Origin not allowed"},403,o);const key=req.headers.get("apikey")||"";if(!key||!keys().has(key))return json({error:"Unauthorized"},401,o);let payload:Record<string,unknown>;try{payload=await req.json()}catch{return json({error:"Invalid JSON"},400,o)}const url=validUrl(payload.url);if(!url)return json({error:"Only approved Aozora Bunko story HTML URLs are allowed"},400,o);const n=Number(payload.maxChars||DEFAULT_MAX),max=Math.max(MIN,Math.min(HARD_MAX,Number.isFinite(n)?Math.round(n):DEFAULT_MAX)),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),10000);try{const r=await fetch(url.toString(),{signal:controller.signal,headers:{"User-Agent":"Sakura Japanese Reading Garden/1.0 (+https://chachinn.github.io/sakura/)"}});if(!r.ok)return json({error:`Source returned HTTP ${r.status}`},502,o);const b=new Uint8Array(await r.arrayBuffer()),html=decode(b,r.headers.get("content-type")||""),ps=paragraphs(html);if(!ps.length)return json({error:"Could not extract the story text"},502,o);const p=passage(ps,max);if(!p.text)return json({error:"Story passage was empty"},502,o);return json({source:"青空文庫",sourceUrl:url.toString(),mode:"verbatim-public-domain-passage",paragraphs:p.paragraphs,text:p.text,charCount:p.charCount,truncated:ps.join("").length>p.charCount},200,o)}catch(e){return json({error:e instanceof DOMException&&e.name==="AbortError"?"Source request timed out":"Source request failed"},502,o)}finally{clearTimeout(timeout)}});